export const Assets = {
  images: {
    logo_nav: require("../../images/png/logo-bg.png"),
    logo_nav_two: require("../../images/png/logo.png"),
    kc_articles: require("../../images/png/kc-articles.png"),
    kc_connect: require("../../images/png/kc-connect.png"),
    kc_dash: require("../../images/png/kc-dash.png"),
    kc_exam: require("../../images/png/kc-exam.png"),
    kc_exams: require("../../images/png/kc-exams.png"),
    kc_home: require("../../images/png/kc-home.png"),
    kc_image: require("../../images/png/kc-image.png"),
    kc_loading: require("../../images/png/kc-loading.png"),
    kc_online: require("../../images/png/kc-online.png"),
    kc_pass: require("../../images/png/kc-pass.png"),
    kc_profile: require("../../images/png/kc-profile.png"),
    kc_register: require("../../images/png/kc-register.png"),
    kc_signup: require("../../images/png/kc-signup.png"),
    kc_text_two: require("../../images/png/kc-text-two.png"),
    kc_welcome_: require("../../images/png/kc-connect.png"),
    pass_gen: require("../../images/png/passGen.png"),
    cal: require("../../images/png/calculator-e.png"),
    more_image_one: require("../../images/png/more_image_one.png"),
    coming_soon: require("../../images/png/com-removebg-preview.png"),
    html_cover: require("../../images/png/html.png"),
    css_cover: require("../../images/png/css.png"),
    vscode_cover: require("../../images/png/vscode.png"),
    intelliJ_cover: require("../../images/png/intelli-j.png"),
    jsbasic_cover: require("../../images/png/jsbasic.png"),
    jsplus_cover: require("../../images/png/js++.png"),
    react_cover: require("../../images/png/react.png"),
    main_cover: require("../../images/png/mainncover.png"),
    img_one: require("../../images/png/imgone.png"),
    img_two: require("../../images/png/imgtwo.png"),
    img_three: require("../../images/png/imgthree.png"),
    nav_logo: require("../../images/png/ekelogo.png"),
    home_image: require("../../images/png/home-image.png"),
    home_banner: require("../../images/png/banner-home.png"),
    apple: require("../../images/png/apple.png"),
    google: require("../../images/png/google.png"),
    skills: require("../../images/png/skills.png"),
    rTransfer: require("../../images/png/rapidtransfer.png"),
    ecobank_pay: require("../../images/png/ecobankpay.png"),
    kc: require("../../images/png/kcc.png"),
    dev_tools: require("../../images/png/devtools.png"),
    twitter: require("../../images/png/twitter.png"),
    mail: require("../../images/png/mail.png"),
    linkedin: require("../../images/png/linkedin.png"),
    whatapps: require("../../images/png/whatsapp.png"),
    line: require("../../images/png/line.png"),
    access: require("../../images/png/access.png"),
    corsesIllustration: require("../../images/png/corsesIllustration.png"),
    aboutimage: require("../../images/png/abotme.png"),
    starticon: require("../../images/png/startmain.png"),
  },
  theme: {
    light: {
      bg: "#ffffff",
      textColor: "#282A94",
    },
    dark: {
      bg: "#000000",
      textColor: "yellow",
    },
  },
  colors: {
    primary: "#E8C547",
    secondary: "#0C0C0C",
    basic: "#4D5061",
    light: "#ffffff",
    auto: "#BCC4D1",
    neat: "#212C2F",
    boldNeat: "#479BE8",
    san: "#161619",
  },
};
